[IMPL] New Alt Manager
momentumdevelopment/cosmos pull request #186
Opened 2022-02-06 15:45 UTC by Wolfsurge

New alt manager. Supports Microsoft, Mojang, and Cracked accounts currently. Might add TheAltening later. Pretty sure this code is OK.

2022-02-06 20:35 UTC, Sxmurai commented on src/main/java/cope/cosmos/client/manager/managers/AltManager.java
> +            if(input != null) {
a space after if

2022-02-06 20:35 UTC, Sxmurai commented on src/main/java/cope/cosmos/client/manager/managers/AltManager.java
> +                    if(input.getList("Alts.Alts") != null) {
a space after if

2022-02-06 20:35 UTC, Sxmurai commented on src/main/java/cope/cosmos/client/manager/managers/AltManager.java
> +                            if(altInfo[2].equalsIgnoreCase("Microsoft")) type = Alt.AltType.Microsoft;
switch case could be used here, also AltType.valueOf() is a thing

2022-02-06 20:36 UTC, Sxmurai commented on src/main/java/cope/cosmos/client/ui/altmanager/AddAltGUI.java
> +        this.loginField = new GuiTextField(1, mc.fontRenderer, this.width / 2 - 100, this.height / 2 - 42, 200, 15);
`this` is not needed

2022-02-06 20:36 UTC, Sxmurai commented on src/main/java/cope/cosmos/client/ui/altmanager/AddAltGUI.java
> +        if(loginField.getText().equals("") && !loginField.isFocused() && loginField.getVisible())
space after if

2022-02-06 20:36 UTC, Sxmurai commented on src/main/java/cope/cosmos/client/ui/altmanager/AddAltGUI.java
> +        if(passwordField.getText().equals("") && !passwordField.isFocused() && passwordField.getVisible())
space after if

2022-02-06 20:37 UTC, Sxmurai commented on src/main/java/cope/cosmos/client/ui/altmanager/AddAltGUI.java
> +        if(passwordField.getText().equals("") && !passwordField.isFocused() && passwordField.getVisible())
also, isEmpty() is a thing instead of .equals("")

2022-02-06 20:37 UTC, Sxmurai commented on src/main/java/cope/cosmos/client/ui/altmanager/AddAltGUI.java
> +                if(!(loginField.getText().isEmpty())) {
space after if

2022-02-06 20:38 UTC, Sxmurai commented on src/main/java/cope/cosmos/client/ui/altmanager/AddAltGUI.java
> +        if(keyCode == Keyboard.KEY_ESCAPE) {
space after if

2022-02-06 20:38 UTC, Sxmurai commented on src/main/java/cope/cosmos/client/ui/altmanager/AddAltGUI.java
> +        if(keyCode == Keyboard.KEY_RETURN) {
space after if

2022-02-06 20:38 UTC, Sxmurai commented on src/main/java/cope/cosmos/client/ui/altmanager/AddAltGUI.java
> +            this.loginField.setFocused(false);
as previously mentioned, do not use `this`

2022-02-06 20:38 UTC, Sxmurai commented on src/main/java/cope/cosmos/client/ui/altmanager/Alt.java
> +                return new Session(result.getProfile().getName(), result.getProfile().getId(), result.getAccessToken(),"legacy");
space before the string

2022-02-06 20:38 UTC, Sxmurai commented on src/main/java/cope/cosmos/client/ui/altmanager/Alt.java
> +        if (getAltType() == AltType.Microsoft) {
use .equals() instead of ==

2022-02-06 20:39 UTC, Sxmurai commented on src/main/java/cope/cosmos/client/ui/altmanager/Alt.java
> +        else if (getAltType() == AltType.Mojang) {
use .equals() instead of ==. could also use a switch case

2022-02-06 20:39 UTC, Sxmurai commented on src/main/java/cope/cosmos/client/ui/altmanager/Alt.java
> +        else if (getAltType() == AltType.Cracked) {
see above, use .equals() instead of ==. could also use a switch case

2022-02-06 20:39 UTC, Sxmurai commented on src/main/java/cope/cosmos/client/ui/altmanager/Alt.java
> +            Random random = new Random();
use ThreadLocalRandom.current() instead of creating a new instance of Random

2022-02-06 20:40 UTC, Sxmurai commented on src/main/java/cope/cosmos/client/ui/altmanager/AltEntry.java
> +        if(isMouseOverButton(mouseX, mouseY))
space after if

2022-02-06 20:40 UTC, Sxmurai commented on src/main/java/cope/cosmos/client/ui/altmanager/AltEntry.java
> +        if(isSelected)
space after if

2022-02-06 20:40 UTC, Sxmurai commented on src/main/java/cope/cosmos/client/ui/altmanager/AltEntry.java
> +        if(getAlt().getAltSession() != null) {
space after if

2022-02-06 20:40 UTC, Sxmurai commented on src/main/java/cope/cosmos/client/ui/altmanager/AltEntry.java
> +            GL11.glPushMatrix();
use static imports (instead of GL11.glPushMatrix() use glPushMatrix() by using a wildcard on the GL11 class)

2022-02-06 20:41 UTC, Sxmurai commented on src/main/java/cope/cosmos/client/ui/altmanager/AltEntry.java
> +        if(getAlt().getAltSession() != null)
space after if

2022-02-06 20:41 UTC, Sxmurai commented on src/main/java/cope/cosmos/client/ui/altmanager/AltEntry.java
> +        if(getAlt().getAltType() != Alt.AltType.Cracked)
space after if

2022-02-06 20:41 UTC, Sxmurai commented on src/main/java/cope/cosmos/client/ui/altmanager/AltEntry.java
> +        if(getAlt().getAltSession() != null) {
space after if

2022-02-06 20:41 UTC, Sxmurai commented on src/main/java/cope/cosmos/client/ui/altmanager/AltManagerGUI.java
> +        this.buttonList.add(new GuiButton(0, scaledResolution.getScaledWidth() / 2 - 150, scaledResolution.getScaledHeight() - 23, 100, 20, "Add Alt"));
do not use `this`

2022-02-06 20:41 UTC, Sxmurai commented on src/main/java/cope/cosmos/client/ui/altmanager/AltManagerGUI.java
> +        if(!AltManager.getAltEntries().isEmpty())
space after if

2022-02-06 20:41 UTC, Sxmurai commented on src/main/java/cope/cosmos/client/ui/altmanager/AltManagerGUI.java
> +        for(AltEntry altEntry : AltManager.getAltEntries())
use forEach instead of a loop

2022-02-06 20:41 UTC, Sxmurai commented on src/main/java/cope/cosmos/client/ui/altmanager/AltManagerGUI.java
> +        if(AltManager.getAltEntries().isEmpty())
space after if

2022-02-06 20:42 UTC, Sxmurai commented on src/main/java/cope/cosmos/client/ui/altmanager/AltManagerGUI.java
> +        if(AltManager.getAltEntries().isEmpty()) return;
space after if. also dont use inline returns

2022-02-06 20:42 UTC, Sxmurai commented on src/main/java/cope/cosmos/client/ui/altmanager/AltManagerGUI.java
> +                for (AltEntry altEntry : AltManager.getAltEntries()) {
use forEach instead of loop

2022-02-06 20:42 UTC, Sxmurai commented on src/main/java/cope/cosmos/client/ui/altmanager/AltManagerGUI.java
> +                for (AltEntry altEntry : AltManager.getAltEntries()) {
use forEach instead of for loop

2022-02-06 20:43 UTC, Sxmurai commented on src/main/java/cope/cosmos/client/ui/altmanager/AltManagerGUI.java
> +                if(getSelectedAltEntry() != null) {
space after if

2022-02-06 20:43 UTC, Sxmurai commented on src/main/java/cope/cosmos/client/ui/altmanager/AltManagerGUI.java
> +                    if(!AltManager.getAltEntries().isEmpty())
space after if

2022-02-06 20:43 UTC, Sxmurai commented on src/main/java/cope/cosmos/client/ui/altmanager/AltManagerGUI.java
> +        for(AltEntry altEntry : AltManager.getAltEntries()) {
space after for

2022-02-06 20:43 UTC, Sxmurai commented on src/main/java/cope/cosmos/client/ui/altmanager/AltManagerGUI.java
> +        for(AltEntry altEntry : AltManager.getAltEntries()) {
space after for, and a space after if in the for loop

2022-02-06 20:44 UTC, Sxmurai commented on src/main/java/cope/cosmos/client/ui/altmanager/AltManagerGUI.java
> +        for(AltEntry altEntry : AltManager.getAltEntries())
could use anyMatch(), but im sure what linus would like to do to. but def a space after for

2022-02-06 20:44 UTC, Sxmurai commented on src/main/java/cope/cosmos/client/ui/altmanager/AltManagerGUI.java
> +        if(keyCode == Keyboard.KEY_ESCAPE) {
space after if

2022-02-06 20:45 UTC, Sxmurai commented on src/main/java/cope/cosmos/client/ui/altmanager/AltManagerGUI.java
> +        for(AltEntry altEntry : AltManager.getAltEntries()) {
space after if

2022-02-06 20:45 UTC, Sxmurai commented on src/main/java/cope/cosmos/client/ui/altmanager/AltManagerGUI.java
> +            if(altEntry.isMouseOverButton(mouseX, mouseY)) {
space after if

2022-02-06 20:45 UTC, Sxmurai commented on src/main/java/cope/cosmos/client/ui/altmanager/AltManagerGUI.java
> +                if(altEntry.isSelected)
space after if

2022-02-06 20:46 UTC, Sxmurai commented on src/main/java/cope/cosmos/client/ui/altmanager/Alt.java
> +    public enum AltType {
use uppercase enum constants instead of "friendly" names

2022-02-06 20:47 UTC, Sxmurai commented on src/main/java/cope/cosmos/client/ui/altmanager/Alt.java
> +            Random random = new Random();
you also dont even need to do this for cracked, you can just do "" for the playerID

2022-02-07 04:13 UTC, notperry12345678902 commented
Remove the Chinese code and this shall be merged.

2022-02-07 13:20 UTC, Wolfsurge commented
I think I did everything except renaming the alt type enum

2022-02-07 15:09 UTC, Sxmurai requested changes
last few things, otherwise it looks good. @linustouchtips will have to double check this all to make sure he doesnt want anything, or catch something i may have missed.

2022-02-07 15:09 UTC, Sxmurai commented on src/main/java/cope/cosmos/client/features/modules/movement/Jesus.java
> +            if(PlayerUtil.isInLiquid())
space after if, it seems i didnt catch this one

2022-02-07 15:09 UTC, Sxmurai commented on src/main/java/cope/cosmos/client/manager/managers/AltManager.java
> + * @author Wolfsurge, linustouchtips
add @since back to javadoc here below author

2022-02-07 15:09 UTC, Sxmurai commented on src/main/java/cope/cosmos/client/manager/managers/AltManager.java
> +                catch (Exception exception) {
add an extra newline here

2022-02-07 15:09 UTC, Sxmurai commented on src/main/java/cope/cosmos/client/manager/managers/AltManager.java
> +        catch (IOException exception) {
add an extra newline here

2022-02-07 15:11 UTC, Sxmurai commented
![image](https://user-images.githubusercontent.com/57580886/152815046-4a09ba26-7c6a-469f-a784-efb676b48928.png)

also, the build failed. there is the stacktrace above ^

2022-02-07 17:04 UTC, linustouchtips commented on src/main/java/cope/cosmos/client/features/modules/movement/Jesus.java
> +            if (PlayerUtil.isInLiquid())
Add curly braces to all if statements, let's keep the code style consistent

2022-02-07 17:35 UTC, merged