[IMPL] NoBob
momentumdevelopment/cosmos pull request #199
Opened 2022-02-08 19:47 UTC by Wolfsurge

Lets you use view bobbing without 'bobbing' the crosshair, e.g. tracers bobbing etc.

2022-02-08 21:09 UTC, Sxmurai commented
EntityRenderer#orientCamera() does that fine when using tracers, but this works too. also, im going to make a review cause linus is gonna want some changes

2022-02-08 21:10 UTC, Wolfsurge commented
yeah ok

2022-02-08 21:12 UTC, Wolfsurge commented
Fuck I need to add a space after if

2022-02-09 03:48 UTC, notperry12345678902 commented
whats a norender

2022-02-09 04:25 UTC, master7720 commented
> whats a norender

xD

2022-02-09 04:25 UTC, master7720 commented
Dude just make it a NoRender setting

2022-02-09 06:48 UTC, Wolfsurge commented
> Dude just make it a NoRender setting

fine

2022-02-09 17:08 UTC, linustouchtips requested changes

2022-02-09 17:08 UTC, linustouchtips commented on src/main/java/cope/cosmos/client/features/modules/visual/NoRender.java
> +        if(crosshairBob.getValue()) {
space

2022-02-09 17:16 UTC, merged