[IMPL] TabGUI
momentumdevelopment/cosmos pull request #207
Opened 2022-03-29 18:33 UTC by Wolfsurge

hopefully this isn't too bad :P

Here's what it looks like
![tabgui](https://user-images.githubusercontent.com/73380591/160681188-bc95f8c2-b74b-442f-8307-867971f57989.png)

2022-03-29 21:48 UTC, master7720 commented
looks great

2022-03-29 21:49 UTC, Wolfsurge commented
cool 👍

@linustouchtips pls merge

2022-03-30 00:10 UTC, Sxmurai commented
Good job, I don't see any code changes from a quick glance. I'll let linus review and push into main.

2022-03-30 15:25 UTC, linustouchtips requested changes
looks good, remember to also merge branch main

2022-03-30 15:25 UTC, linustouchtips commented on src/main/java/cope/cosmos/client/features/modules/client/HUDModule.java
> +                Cosmos.INSTANCE.getTabGUI().onKeyPress(event);
use getCosmos()

2022-03-30 15:25 UTC, linustouchtips commented on src/main/java/cope/cosmos/client/features/modules/client/HUDModule.java
> +            Cosmos.INSTANCE.getTabGUI().render();
use getCosmos()

2022-03-30 15:25 UTC, linustouchtips commented on src/main/java/cope/cosmos/client/ui/tabgui/TabGUI.java
> + */
date?

2022-03-30 15:25 UTC, linustouchtips commented on src/main/java/cope/cosmos/client/ui/tabgui/component/CategoryComponent.java
> +        for (Module module : Cosmos.INSTANCE.getModuleManager().getModules(module -> module.getCategory().equals(category))) {
use getCosmos()

2022-03-30 20:18 UTC, merged

2022-03-30 20:25 UTC, master7720 commented on src/main/java/cope/cosmos/client/ui/tabgui/component/CategoryComponent.java
> + * @author Wolfsurge
doesnt really need a date tbh

2022-03-30 20:25 UTC, Wolfsurge commented on src/main/java/cope/cosmos/client/ui/tabgui/component/CategoryComponent.java
> + * @author Wolfsurge
oh well i already fixed i

2022-03-30 20:50 UTC, linustouchtips commented on src/main/java/cope/cosmos/client/ui/tabgui/component/CategoryComponent.java
> + * @author Wolfsurge
> doesnt really need a date tbh

OMG STFU