Added Moving Fakeplayer
momentumdevelopment/cosmos pull request #232
Opened 2022-07-17 23:14 UTC by EBSmash

2022-07-17 23:15 UTC, EBSmash commented
#31

2022-07-17 23:22 UTC, Wolfsurge requested changes
Just some things I noticed

linus/aesthetical can probably see some more inconsistencies etc.

2022-07-17 23:22 UTC, Wolfsurge commented on src/main/java/cope/cosmos/client/features/modules/misc/FakePlayerModule.java
>   * @author linustouchtips
Add your name here instead of below

2022-07-17 23:22 UTC, Wolfsurge commented on src/main/java/cope/cosmos/client/features/modules/misc/FakePlayerModule.java
> +    EntityOtherPlayerMP fakePlayer;
Declare as private

2022-07-17 23:22 UTC, Wolfsurge commented on src/main/java/cope/cosmos/client/features/modules/misc/FakePlayerModule.java
> +            if (move.getValue()) travel(fakePlayer.moveStrafing, fakePlayer.moveVertical, fakePlayer.moveForward);
Use separate lines (add brackets)

2022-07-17 23:22 UTC, Wolfsurge commented on src/main/java/cope/cosmos/client/features/modules/misc/FakePlayerModule.java
> +            if (move.getValue()) travel(fakePlayer.moveStrafing, fakePlayer.moveVertical, fakePlayer.moveForward);
Also, I'm assuming you can't (cannot check rn), but couldn't you call the travel method directly from the fake player (`fakePlayer.travel()`)?

2022-07-17 23:23 UTC, Wolfsurge commented on src/main/java/cope/cosmos/client/features/modules/misc/FakePlayerModule.java
>   * @author linustouchtips
wrong line woops, meant the line with `@author` on

2022-07-18 00:31 UTC, Sxmurai commented on src/main/java/cope/cosmos/client/features/modules/misc/FakePlayerModule.java
> +            Random random = new Random();
Don't create a random every update

2022-07-18 00:32 UTC, Sxmurai commented
Also do you have a video of this? Like a short clip from streamable or medal so I can see its behavior?

2022-07-18 16:15 UTC, Wolfsurge commented on src/main/java/cope/cosmos/client/features/modules/misc/FakePlayerModule.java
>   * @author linustouchtips
No, the whole thing should look like `@author linustouchtips, EBSmash

2022-07-25 12:10 UTC, EBSmash commented
It should be good now.

heres a video of it
https://user-images.githubusercontent.com/53373788/180774645-ac5582c7-9c08-4adb-9bb9-40979c2978eb.mp4

2022-07-27 16:47 UTC, EBSmash commented
Any updates on this @Sxmurai

2022-07-29 19:22 UTC, TwoThreeTwo commented
Can you add a speed slider? ie: if the amount is increased so is the player speed vice versa

2022-07-29 19:24 UTC, EBSmash commented
Of course, I'll add that when I get home

2022-07-29 19:26 UTC, TwoThreeTwo commented
👍

2022-08-20 08:19 UTC, GentlemanMC commented
dead client

2022-08-20 08:19 UTC, TwoThreeTwo commented
No, there's just a private beta version that actually updates

2022-08-21 00:59 UTC, EBSmash commented
I shit, I forgor about this lmao

2022-08-26 23:28 UTC, TwoThreeTwo commented
Lmao

2022-11-09 18:19 UTC, closed without merging